const donuts = [
    {
        id: 1,
        name: "Biscoff Caramel",
        price: 4.50,
        image: "images/biscoff.png",
        category: "popular",
        calories: 380,
        protein: "5g",
        carbs: "52g (Sugars: 28g)",
        fat: "17g (Saturated: 8g)",
        sodium: "220mg",
        ingredients: "Wheat flour, sugar, eggs, butter, vegetable oil, yeast, milk, salt, cinnamon, vanilla extract, Lotus Biscoff spread (caramelised biscuits 38%, vegetable oils, sugar, soy flour, leavening agents, salt, cinnamon), caramel sauce.",
        contains: "Gluten (wheat), dairy, eggs, soy. May contain traces of: Nuts (including peanuts and tree nuts), sesame."
    },
    {
        id: 2,
        name: "Pistachio Crunch",
        price: 4.50,
        image: "images/pistachio.png",
        category: "popular",
        calories: 370,
        protein: "7g",
        carbs: "45g (Sugars: 22g)",
        fat: "18g (Saturated: 7g)",
        sodium: "190mg",
        ingredients: "Wheat flour, sugar, eggs, butter, vegetable oil, yeast, milk, salt, vanilla extract, pistachio paste, crushed pistachios, white chocolate coating.",
        contains: "Gluten (wheat), dairy, eggs, tree nuts (pistachios). May contain traces of: Peanuts, sesame."
    },
    {
        id: 3,
        name: "Original Glaze",
        price: 4.50,
        image: "images/original-glaze.png",
        category: "popular",
        calories: 310,
        protein: "4g",
        carbs: "44g (Sugars: 20g)",
        fat: "13g (Saturated: 6g)",
        sodium: "180mg",
        ingredients: "Wheat flour, sugar, eggs, butter, vegetable oil, yeast, milk, salt, vanilla extract, icing sugar, water.",
        contains: "Gluten (wheat), dairy, eggs. May contain traces of: Nuts, soy, sesame."
    },
    {
        id: 4,
        name: "Hojicha Glaze",
        price: 4.50,
        image: "images/tea.png",
        category: "new",
        calories: 330,
        protein: "5g",
        carbs: "46g (Sugars: 22g)",
        fat: "14g (Saturated: 6g)",
        sodium: "185mg",
        ingredients: "Wheat flour, sugar, eggs, butter, vegetable oil, yeast, milk, salt, vanilla extract, roasted hojicha green tea powder, white chocolate glaze.",
        contains: "Gluten (wheat), dairy, eggs. May contain traces of: Nuts, soy, sesame."
    },
    {
        id: 5,
        name: "Matcha Glaze",
        price: 4.50,
        image: "images/matcha.png",
        category: "popular",
        calories: 340,
        protein: "5g",
        carbs: "47g (Sugars: 23g)",
        fat: "14g (Saturated: 6g)",
        sodium: "185mg",
        ingredients: "Wheat flour, sugar, eggs, butter, vegetable oil, yeast, milk, salt, vanilla extract, ceremonial grade matcha powder, white chocolate glaze.",
        contains: "Gluten (wheat), dairy, eggs. May contain traces of: Nuts, soy, sesame."
    },
    {
        id: 6,
        name: "Strawberry Vanilla",
        price: 4.50,
        image: "images/strawberry.png",
        category: "best-sellers",
        calories: 350,
        protein: "4g",
        carbs: "50g (Sugars: 26g)",
        fat: "14g (Saturated: 7g)",
        sodium: "175mg",
        ingredients: "Wheat flour, sugar, eggs, butter, vegetable oil, yeast, milk, salt, vanilla extract, strawberry jam, vanilla glaze, freeze-dried strawberry pieces.",
        contains: "Gluten (wheat), dairy, eggs. May contain traces of: Nuts, soy, sesame."
    },
    {
        id: 7,
        name: "Dark Chocolate",
        price: 4.50,
        image: "images/chocolate.png",
        category: "best-sellers",
        calories: 395,
        protein: "6g",
        carbs: "50g (Sugars: 28g)",
        fat: "20g (Saturated: 10g)",
        sodium: "210mg",
        ingredients: "Wheat flour, sugar, eggs, butter, vegetable oil, yeast, milk, salt, vanilla extract, dark chocolate (cocoa solids 55%), cocoa powder, chocolate glaze.",
        contains: "Gluten (wheat), dairy, eggs, soy. May contain traces of: Nuts, sesame."
    }
];